### ISSUE TITLE
yarn start dà errore

### ISSUE THREAD

**Issue by marcoscale98** [pagopa/io-dev-api-server#136]
Ho seguito passo passo il README file, ma quando faccio `yarn start` mi dà diversi errori e non capisco il perchè.

Vi metto anche il risultato del `yarn install` che magari può chiarire
```
marco@23f599ca-c301-45c1-9de8-ed2f1ef36473 io-dev-api-server % yarn install
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
warning Resolution field "fp-ts@1.19.5" is incompatible with requested version "fp-ts@1.17.4"
warning Resolution field "fp-ts@1.19.5" is incompatible with requested version "fp-ts@1.17.4"
warning Resolution field "fp-ts@1.19.5" is incompatible with requested version "fp-ts@1.12.0"
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "cli-ux > @oclif/command@1.8.0" has unmet peer dependency "@oclif/config@^1".
warning "italia-tslint-rules > tslint-eslint-rules@5.4.0" has incorrect peer dependency "typescript@^2.2.0 || ^3.0.0".
warning "italia-tslint-rules > tslint-immutable@5.5.2" has incorrect peer dependency "typescript@^2.8.0 || ^3.0.0".
warning "italia-tslint-rules > tslint-sonarts@1.9.0" has incorrect peer dependency "typescript@^2.2 || ^3.0".
warning "italia-tslint-rules > typestrict > tslint-microsoft-contrib@5.2.1" has incorrect peer dependency "typescript@^2.1.0 || ^3.0.0".
[4/4] 🔨  Building fresh packages...
✨  Done in 2.36s.
```
Risultato del `yarn start`:
```
marco@23f599ca-c301-45c1-9de8-ed2f1ef36473 io-dev-api-server % yarn start
yarn run v1.22.17
$ ts-node src/start.ts
/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/config.ts:9:30 - error TS2307: Cannot find module '../generated/definitions/backend/EmailAddress' or its corresponding type declarations.

9 import { EmailAddress } from "../generated/definitions/backend/EmailAddress";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/config.ts:10:39 - error TS2307: Cannot find module '../generated/definitions/backend/PreferredLanguage' or its corresponding type declarations.

10 import { PreferredLanguageEnum } from "../generated/definitions/backend/PreferredLanguage";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticText: "\x1B[96msrc/config.ts\x1B[0m:\x1B[93m9\x1B[0m:\x1B[93m30\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module '../generated/definitions/backend/EmailAddress' or its corresponding type declarations.\n" +
    '\n' +
    '\x1B[7m9\x1B[0m import { EmailAddress } from "../generated/definitions/backend/EmailAddress";\n' +
    '\x1B[7m \x1B[0m \x1B[91m                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n' +
    "\x1B[96msrc/config.ts\x1B[0m:\x1B[93m10\x1B[0m:\x1B[93m39\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module '../generated/definitions/backend/PreferredLanguage' or its corresponding type declarations.\n" +
    '\n' +
    '\x1B[7m10\x1B[0m import { PreferredLanguageEnum } from "../generated/definitions/backend/PreferredLanguage";\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n',
  diagnosticCodes: [ 2307, 2307 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
marco@23f599ca-c301-45c1-9de8-ed2f1ef36473 io-dev-api-server % yarn install
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
warning Resolution field "fp-ts@1.19.5" is incompatible with requested version "fp-ts@1.17.4"
warning Resolution field "fp-ts@1.19.5" is incompatible with requested version "fp-ts@1.17.4"
warning Resolution field "fp-ts@1.19.5" is incompatible with requested version "fp-ts@1.12.0"
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "cli-ux > @oclif/command@1.8.0" has unmet peer dependency "@oclif/config@^1".
warning "italia-tslint-rules > tslint-eslint-rules@5.4.0" has incorrect peer dependency "typescript@^2.2.0 || ^3.0.0".
warning "italia-tslint-rules > tslint-immutable@5.5.2" has incorrect peer dependency "typescript@^2.8.0 || ^3.0.0".
warning "italia-tslint-rules > tslint-sonarts@1.9.0" has incorrect peer dependency "typescript@^2.2 || ^3.0".
warning "italia-tslint-rules > typestrict > tslint-microsoft-contrib@5.2.1" has incorrect peer dependency "typescript@^2.1.0 || ^3.0.0".
[4/4] 🔨  Building fresh packages...
✨  Done in 3.56s.
marco@23f599ca-c301-45c1-9de8-ed2f1ef36473 io-dev-api-server % yarn start  
yarn run v1.22.17
$ ts-node src/start.ts
/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/config.ts:9:30 - error TS2307: Cannot find module '../generated/definitions/backend/EmailAddress' or its corresponding type declarations.

9 import { EmailAddress } from "../generated/definitions/backend/EmailAddress";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/config.ts:10:39 - error TS2307: Cannot find module '../generated/definitions/backend/PreferredLanguage' or its corresponding type declarations.

10 import { PreferredLanguageEnum } from "../generated/definitions/backend/PreferredLanguage";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/marco/Documents/GitHub/io-dev-api-server/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticText: "\x1B[96msrc/config.ts\x1B[0m:\x1B[93m9\x1B[0m:\x1B[93m30\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module '../generated/definitions/backend/EmailAddress' or its corresponding type declarations.\n" +
    '\n' +
    '\x1B[7m9\x1B[0m import { EmailAddress } from "../generated/definitions/backend/EmailAddress";\n' +
    '\x1B[7m \x1B[0m \x1B[91m                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n' +
    "\x1B[96msrc/config.ts\x1B[0m:\x1B[93m10\x1B[0m:\x1B[93m39\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module '../generated/definitions/backend/PreferredLanguage' or its corresponding type declarations.\n" +
    '\n' +
    '\x1B[7m10\x1B[0m import { PreferredLanguageEnum } from "../generated/definitions/backend/PreferredLanguage";\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n',
  diagnosticCodes: [ 2307, 2307 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
OS: Mac OS 12.1
Installato nodenv con brew, settato tutto correttamente e installata la versione di node presente nel file `.node-version`
Qualcuno sa aiutarmi? Grazie

**Comment by lucacavallaro** [comment]
Ciao! 

Devi eseguire il comando "yarn generate:all" dopo aver installato le dipendenze
